### ISSUE TITLE
Mostly(?) code of Joe Allen?

### ISSUE THREAD

**Issue by ratopi** [crozone/relaysbc-programs#4]
AFAIS is this repository based on the code on

https://sourceforge.net/p/relaysbc/code/ci/default/tree/

Therefore would be nice, to mention Joe Allen as author (and commiter?) in the git history :-)

**Comment by crozone** [comment]
As per the project README:

> This repository contains community contributed programs for the sbrc, as well as a mirror of the sample code, utility programs, and firmware written by Joe Allen.

> The original SourceForge project page can be found here: https://sourceforge.net/projects/relaysbc/

**Comment by crozone** [comment]
As per the project README:

> This repository contains community contributed programs for the sbrc, as well as a mirror of the sample code, utility programs, and firmware written by Joe Allen.

> The original SourceForge project page can be found here: https://sourceforge.net/projects/relaysbc/

This project is not quite a direct fork of the sourceforge repository. Originally it started out just to store community contributed programs, such as my Tetris implementation and Dag's Pi program, which previously only existed on the sourceforge forums.

At some point I had to modify Joe's assembler and emulator to add additional features that I needed. This is when Joe's code was added and forked, since it didn't make sense to ship code that can't be assembled. Perhaps, I should make it clearer that this is a modified version of the sourceforge code to reduce confusion.

For reference, the commit where the sourceforge code was added is https://github.com/crozone/relaysbc-programs/commit/3d26250b4a686206b02abdff9a7b7fbcdd04ff1a

Joe is explicitly credited as the author of his work in the README under each program heading and the original GPL v2 license has been maintained and complied with for his work. Sub directories also contain READMEs that provide attribution, as do the files themselves.

> Therefore would be nice, to mention Joe Allen as author (and commiter?) in the git history :-)

Unfortunately, I can't really accomplish this. I cannot maintain any git history from the sourceforge repo because the sourceforge project is mercurial, not git, and the two projects have different histories anyway. [Joe](https://github.com/jhallen) doesn't have the assembler or simulator as a github project, so I can't directly fork and modify it. Therefore, I am necessarily the author of those commits. I could modify the commit to more explicitly add attribution to the commit message, but it would rewriting the entire commit history and IMHO is largely unnecessary given the attribution already provided. AFAIK, I am fully complying with the original project license.

If you like I could contact Joe for guidance on how to proceed. It would be nice if the sourceforge code was on his github so it could be easily forked and contributed to.

**Comment by ratopi** [comment]
Thanks a lot for your answer.  Your arguments make sense.  Perhaps I was too strict about it. The approach you have taken is pragmatic but correct. I also realize that changing the git history would probably create more problems than it would solve.
